# Generated by Django 5.2.8 on 2025-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
